version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB= alkemy_challenge
      - POSTGRES_USER= admin
      - POSTGRES_PASSWORD= admin
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data